stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/001_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/001_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/001_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/002_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/002_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/002_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/003_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/003_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/003_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/004_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/004_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/004_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/005_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/005_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/005_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/006_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/006_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/006_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/007_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/007_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/007_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/008_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/008_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/008_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/009_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/009_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/009_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/010_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/010_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/010_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/011_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/011_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/011_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/012_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/012_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/012_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/013_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/013_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/013_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/014_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/014_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/014_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/015_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/015_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/015_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/016_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/016_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/016_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/017_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/017_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/017_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/018_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/018_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/018_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/019_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/019_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/019_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/020_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/020_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/020_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/021_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/021_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/021_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/022_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/022_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/022_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/023_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/023_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/023_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/024_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/024_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/024_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/025_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/025_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/025_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/026_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/026_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/026_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/027_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/027_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/027_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/028_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/028_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/028_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/029_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/029_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/029_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/030_walk_irregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/030_walk_regular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/030_walk_semiregular_15_clemson_ped_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P01_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P01_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P02_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P02_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P03_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P03_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P04_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P04_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P05_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P05_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P06_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P06_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P07_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P07_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P08_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P08_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P09_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P09_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P10_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P10_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P11_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P11_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P12_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P12_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P13_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P13_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P14_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P14_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P15_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P15_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P16_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P16_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P17_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P17_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P18_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P18_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P19_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P19_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P20_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P20_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P21_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P21_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P22_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P22_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P23_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P23_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P24_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P24_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P25_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P25_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P26_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P26_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P27_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P27_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P28_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P28_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P29_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P29_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P30_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P30_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P31_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P31_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P32_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P32_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P33_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P33_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P34_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P34_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P35_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P35_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P36_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P36_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P37_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P37_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P38_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P38_25_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P39_100_oxwalk_.csv -o results/stepcount
stepcount /Users/lilykoffman/Documents/step_algorithms/data/processed/stepcount_data/P39_25_oxwalk_.csv -o results/stepcount
