stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_001_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_001_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_001_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_002_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_002_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_002_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_003_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_003_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_003_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_004_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_004_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_004_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_005_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_005_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_005_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_006_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_006_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_006_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_007_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_007_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_007_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_008_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_008_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_008_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_009_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_009_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_009_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_010_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_010_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_010_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_011_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_011_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_011_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_012_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_012_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_012_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_013_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_013_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_013_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_014_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_014_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_014_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_015_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_015_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_015_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_016_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_016_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_016_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_017_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_017_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_017_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_018_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_018_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_018_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_019_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_019_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_019_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_020_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_020_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_020_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_021_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_021_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_021_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_022_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_022_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_022_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_023_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_023_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_023_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_024_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_024_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_024_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_025_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_025_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_025_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_026_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_026_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_026_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_027_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_027_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_027_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_028_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_028_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_028_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_029_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_029_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_029_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_030_irregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_030_regular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_030_semiregular_15Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P01_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P01_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P02_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P02_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P03_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P03_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P04_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P04_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P05_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P05_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P06_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P06_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P07_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P07_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P08_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P08_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P09_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P09_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P10_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P10_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P11_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P11_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P12_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P12_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P13_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P13_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P14_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P14_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P15_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P15_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P16_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P16_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P17_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P17_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P18_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P18_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P19_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P19_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P20_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P20_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P21_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P21_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P22_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P22_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P23_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P23_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P24_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P24_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P25_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P25_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P26_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P26_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P27_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P27_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P28_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P28_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P29_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P29_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P30_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P30_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P31_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P31_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P32_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P32_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P33_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P33_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P34_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P34_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P35_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P35_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P36_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P36_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P37_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P37_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P38_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P38_25Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P39_100Hz.csv -o results/stepcount/original
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/original/acc_P39_25Hz.csv -o results/stepcount/original
