stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_001_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_001_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_001_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_002_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_002_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_002_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_003_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_003_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_003_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_004_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_004_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_004_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_005_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_005_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_005_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_006_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_006_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_006_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_007_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_007_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_007_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_008_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_008_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_008_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_009_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_009_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_009_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_010_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_010_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_010_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_011_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_011_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_011_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_012_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_012_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_012_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_013_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_013_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_013_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_014_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_014_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_014_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_015_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_015_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_015_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_016_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_016_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_016_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_017_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_017_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_017_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_018_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_018_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_018_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_019_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_019_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_019_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_020_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_020_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_020_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_021_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_021_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_021_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_022_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_022_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_022_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_023_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_023_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_023_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_024_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_024_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_024_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_025_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_025_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_025_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_026_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_026_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_026_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_027_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_027_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_027_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_028_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_028_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_028_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_029_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_029_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_029_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_030_irregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_030_regular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_030_semiregular_15to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P01_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P01_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P02_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P02_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P03_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P03_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P04_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P04_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P05_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P05_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P06_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P06_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P07_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P07_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P08_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P08_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P09_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P09_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P10_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P10_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P11_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P11_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P12_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P12_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P13_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P13_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P14_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P14_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P15_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P15_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P16_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P16_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P17_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P17_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P18_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P18_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P19_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P19_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P20_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P20_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P21_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P21_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P22_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P22_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P23_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P23_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P24_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P24_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P25_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P25_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P26_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P26_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P27_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P27_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P28_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P28_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P29_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P29_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P30_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P30_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P31_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P31_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P32_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P32_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P33_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P33_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P34_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P34_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P35_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P35_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P36_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P36_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P37_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P37_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P38_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P38_25to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P39_100to30Hz.csv -o results/stepcount/resampled
stepcount /Users/lilykoffman/Documents/step_algorithms/data/stepcount/resampled/acc_P39_25to30Hz.csv -o results/stepcount/resampled
